version: '3'

services:

  api: #Настройки для нашего арі 

    restart: always #api всегда будет перезапускаться
    build: ./api #путь сборки

    ports: #порт
      - 5555:5000 
    depends_on: #указывает, должен ли сервис перед запуском ждать другие
      - mysql
  frontend: #Настройки для нашего frontend 
    restart: always #frontend всегда будет перезапускаться
    build: ./frontend #путь сборки
    ports:  #порт
      - 8954:8954
  mysql: #Настройки для нашего mysql 
    restart: always #mysql всегда будет перезапускаться
    image: mysql #выбор базы данных
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=time_db
    volumes:
      - mysql_data:/var/lib/mysql 
  adminer: #Настройки для нашего adminer
    restart: always #всегда будет перезапускаться
    image: adminer
    ports: #порт
      - 8888:8080
    depends_on:
      - mysql
volumes:
  mysql_data: